### ISSUE TITLE
关于102中有个错误

### ISSUE THREAD

**Issue by lvfangren** [skyyen999/leetcodeWithJS#4]
可能你这个库已经不更了，但是如果你看到的话，希望能改下。102中13行  while(list.length > 0)应该是
  while(waitlist.length > 0)

今天也是卡在这道题上，百度到你的gitbook，非常感谢解答，自己也能解决问题了。第一次写Issue，忘采纳！

**Comment by skyyen999** [comment]
已更新 感謝修正
